### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by damhiya** [damhiya/nixos-configuration#1]
## XMonad
- [x] Screenshot for focused window
- [x] gtk/qt theme
- [ ] Use `xmonad-contrib`
- [ ] Generate fresh screenshot file name
- [ ] `nixos-profile` : distinguish default, booted, current system
- [ ] declarative password management (agenix or sops-nix)
- [ ] Apply ephemeral root
- [ ] libinput config for wacom
- [ ] pipewire/wireplumber config
